name: statusbarz
description: A Flutter package for dynamically changing status bar color
version: 0.0.1
author: Juho Torkkeli<juho.torkkeli@icloud.com>, Onnimanni Hannonen<onnari11@gmail.com>
homepage: mapventure.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
